.TH GEOMYS "1" "July 2026" "geomys 0.2.0" "User Commands"
.SH NAME
geomys \- A Gopher web browser using shell script
.SH SYNOPSIS
.B geomys
[\fI\,URL\/\fR]\fI\,|\/\fR[\fI\,OPTION\/\fR]
.SH DESCRIPTION
geomys v0.2.0: Browse the gopher web on any POSIX compatible terminal.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help
.TP
\fB\-v\fR, \fB\-\-version\fR
show version info
.SH COMMANDS
These are the default keybindings to use while running geomys:
.TP
\fBq
quit
.TP
\fB\uparrow/\downarrow
select previous/next link (scroll on text pages)
.TP
\fB\leftarrow/\rightarrow
go back/forward in history
.TP
\fBEnter
follow the selected link
.TP
\fBPgUp/PgDn
scroll the page
.TP
\fBr
reload current page
.TP
\fBb
go back one page (same as left arrow)
.TP

\fBu
jump one path segment up
.TP
\fBo
open an address
.TP
\fBs
save current page
.TP
\fBH
go to homepage
.TP
\fBm
add bookmark
.TP
\fBM
go to a bookmark
.TP
\fBK
remove bookmark for current url
.SH ENVIRONMENT
Geomys uses 2 environment variables to help debugging and tracing its execution.
.TP
\fIdebug
To start geomys in debug mode
.TP
\fItrace
To start geomys with tracing activated
.SH REQUIREMENTS
Geomys needs one of \fBnc\fR, \fBnetcat\fR, \fBncat\fR, or \fBsocat\fR to open TCP
connections to gopher servers (default port 70).
.SH CONFIGURATION
You can setup a config file at \fI$XDG_CONFIG_DIR/geomys/geomys.conf\fR to configure \fBgeomys\fR the way you like.
The file uses a simple \fBkey=value\fR style, see the complete example for the default values below.
.PP
.EX
margin=8
homepage="gopher.floodgap.com/1/"
sty_info='\e033[2m'
sty_error='\e033[31;1m'
sty_selected='\e033[7m'
sty_search='\e033[33;1m'
sty_dir='\e033[34;1m'
sty_text='\e033[39m'
sty_bin='\e033[31m'
sty_html='\e033[32m'
sty_image='\e033[33m'
openkey='o'
openlocalkey='O'
refreshkey='r'
backkey='b'
quitkey='q'
markkey='m'
gomarkkey='M'
delmarkkey='K'
goupkey='u'
homekey='H'
savekey='s'
.EE
.SH GOPHER ITEM TYPES
Menus render plain display text with no link numbers or arrow markers.
Up/down move the selection; left/right move through history; Enter follows
the selected link. Selection reverse video keeps the link's colors (for
example a blue directory inverts as blue) and does not include the leading
margin. Directories end with \fB/\fR.
.TP
type 0
plain text file
.TP
type 1
gopher menu / directory (name ends with /)
.TP
type 7
search item (prompts for a query)
.TP
type h
HTML or external URL (not followed in-browser)
.TP
types 9, g, I
binary or media; offered as a download
.SH EXAMPLES
.TP
geomys
Start browsing the default webpage
.TP
geomys gopher.floodgap.com
Start browsing Floodgap
.TP
geomys gopher://gopherpedia.com/1/
Open Gopherpedia
.TP
geomys \-\-help
Show help
.SH AUTHOR
Written by Brian Lee Mayer.
.SH "REPORTING BUGS"
Report bugs to: bleemayer@gmail.com
.br
Home page: <https://www.github.com/blmayer/geomys/>
.SH COPYRIGHT
Copyright \(co 2026 Brian Mayer.
License MIT: MIT License <https://opensource.org/licenses/MIT>
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.SH SEE ALSO
.BR ereandel (1)
